dist: xenial
sudo: required
before_install:
  - sudo apt-get install libice-dev
  - sudo apt-get install libice6
  - sudo apt-get install freeglut3-dev
  - sudo apt-get install cmake
  - sudo apt-get install zeroc-ice-all-dev zeroc-ice-all-runtime zeroc-ice-slice zeroc-ice-utils

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

install:

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
